# Generated by Django 2.2.4 on 2020-09-15 15:30

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icons', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Typy produktów',
                'verbose_name_plural': 'Typy produktów',
            },
        ),
        migrations.CreateModel(
            name='NewOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name_from', models.CharField(max_length=500)),
                ('org_latitude_form', models.IntegerField()),
                ('org_longitude_from', models.IntegerField()),
                ('location_name_to', models.CharField(max_length=500)),
                ('org_latitude_to', models.IntegerField()),
                ('org_longitude_to', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('image_1', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='profile-pictures')),
                ('image_2', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='profile-pictures')),
                ('image_3', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='profile-pictures')),
                ('items_descriptions', models.TextField()),
                ('width', models.PositiveIntegerField()),
                ('depth', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('weight', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('country_user', models.CharField(max_length=100)),
                ('unique_url', models.URLField()),
                ('custom_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.TypeProduct')),
            ],
        ),
    ]
