# Generated by Django 2.2 on 2020-10-16 19:42

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nazwa kategorii')),
                ('displayed_in_navbar', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Kategorie',
                'verbose_name_plural': 'Kategorie',
            },
        ),
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=500, verbose_name='Nazwa firmy')),
                ('company_phone', models.CharField(max_length=30, verbose_name='Telefon kontaktowy')),
                ('company_email', models.EmailField(max_length=254, verbose_name='Adres email')),
                ('description', models.TextField(verbose_name='Opis firmy')),
                ('nip', models.CharField(max_length=20, verbose_name='NIP')),
                ('location', models.CharField(max_length=500)),
                ('package', models.CharField(max_length=50, verbose_name='Pakiet')),
                ('blocked', models.CharField(max_length=50, verbose_name='Zablokowany')),
                ('logo', models.ImageField(upload_to='', verbose_name='Logo')),
                ('thumbnail', models.ImageField(upload_to='', verbose_name='Miniatura')),
                ('licence', models.FileField(upload_to='', verbose_name='Licencja')),
                ('contact_person', models.CharField(max_length=50, verbose_name='Osoba kontaktowa')),
                ('directions_supported', models.CharField(max_length=500)),
                ('vehicle_fleet', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Właściciel')),
            ],
            options={
                'verbose_name': 'Firmy',
                'verbose_name_plural': 'Firmy',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='NewOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_product', models.CharField(max_length=500)),
                ('location_name_from', models.CharField(max_length=500, verbose_name='Lokalizacja nadawcy')),
                ('org_latitude_form', models.CharField(max_length=500, verbose_name='Współrzedne nadawcy (Szerokość geograficzna)')),
                ('org_longitude_from', models.CharField(max_length=500, verbose_name='Współrzedne nadawcy (Długość geograficzna)')),
                ('location_name_to', models.CharField(max_length=500, verbose_name='Lokalizacja odbiorcy')),
                ('org_latitude_to', models.CharField(max_length=500, verbose_name='Współrzedne odbiorcy (Szerokość geograficzna)')),
                ('org_longitude_to', models.CharField(max_length=500, verbose_name='Współrzedne odbiorcy (Długość geograficzna)')),
                ('distance', models.CharField(max_length=500, verbose_name='Odległość między punktami')),
                ('date', models.CharField(max_length=50, verbose_name='Data wysłania paczki')),
                ('image_1', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='profile-pictures', verbose_name='Zdjęcie poglądowe 1')),
                ('image_2', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='profile-pictures', verbose_name='Zdjęcie poglądowe 2')),
                ('image_3', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='profile-pictures', verbose_name='Zdjęcie poglądowe 3')),
                ('items_descriptions', models.TextField(blank=True, verbose_name='Opis przedmiotu')),
                ('width', models.IntegerField(verbose_name='Szerokość paczki')),
                ('depth', models.IntegerField(verbose_name='Długość paczki')),
                ('height', models.IntegerField(verbose_name='Wysokość paczki')),
                ('weight', models.IntegerField(verbose_name='Waga paczki')),
                ('email', models.EmailField(max_length=254, verbose_name='Adres email')),
                ('phone', models.CharField(max_length=30, verbose_name='Numer telefonu')),
                ('contact_person', models.CharField(max_length=50)),
                ('unique_url', models.URLField(blank=True, verbose_name='URL przesyłki')),
                ('custom_id', models.CharField(blank=True, max_length=500, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True, verbose_name='Cena')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data edycji')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wyceny',
                'verbose_name_plural': 'Wyceny',
            },
        ),
        migrations.CreateModel(
            name='Parametrs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_obj', models.IntegerField()),
                ('par_name', models.CharField(max_length=200)),
                ('par_value', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('par_active', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms', ckeditor.fields.RichTextField(verbose_name='Polityka prywatności')),
                ('conditions', ckeditor.fields.RichTextField(verbose_name='Regulamin strony')),
            ],
            options={
                'verbose_name': 'Polityka prywatności i regulamin strony',
                'verbose_name_plural': 'Polityka prywatności i regulamin strony',
            },
        ),
        migrations.CreateModel(
            name='TypeProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nazwa typu produktu')),
                ('icons', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Zdjęcie')),
            ],
            options={
                'verbose_name': 'Typy produktów',
                'verbose_name_plural': 'Typy produktów',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Cena')),
                ('package', models.CharField(max_length=50, verbose_name='Pakiet')),
                ('status', models.CharField(max_length=50, verbose_name='Status płatności')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.CompanyUser', verbose_name='Własciciel')),
            ],
            options={
                'verbose_name': 'Płatności i statusy',
                'verbose_name_plural': 'Płatności i statusy',
            },
        ),
        migrations.CreateModel(
            name='OfferResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Cena')),
                ('date', models.DateTimeField(verbose_name='Data')),
                ('comments', models.TextField(verbose_name='Komentarz')),
                ('displayed', models.BooleanField(default=True, verbose_name='Pokaż oferte')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.CompanyUser', verbose_name='Firma')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.NewOrder', verbose_name='Właściciel')),
            ],
            options={
                'verbose_name': 'Odpowiedzi na oferty',
                'verbose_name_plural': 'Odpowiedzi na oferty',
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50, verbose_name='Temat postu')),
                ('sub_title', models.TextField()),
                ('bg_img', imagekit.models.fields.ProcessedImageField(upload_to='profile-pictures')),
                ('img', imagekit.models.fields.ProcessedImageField(upload_to='profile-pictures', verbose_name='Zdjęcie artykułu')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Treść postu')),
                ('owner', models.CharField(max_length=75, verbose_name='Autor postu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data edycji')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Category', verbose_name='Kategoria')),
            ],
            options={
                'verbose_name': 'NewsLetter/Blog - artykuły',
                'verbose_name_plural': 'NewsLetter/Blog - artykuły',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Coments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, verbose_name='Nazwa użytkownika')),
                ('content', models.CharField(max_length=50, verbose_name='Treść komentarza')),
                ('displayed', models.BooleanField(verbose_name='Pokaż komentarz')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Newsletter', verbose_name='Post')),
            ],
            options={
                'verbose_name': 'Komentarze',
                'verbose_name_plural': 'Komentarze',
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date', models.DateTimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Instancje czatu',
                'verbose_name_plural': 'Instancje czatu',
            },
        ),
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('change', models.TextField()),
                ('date', models.DateTimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Logi zmian',
                'verbose_name_plural': 'Logi zmian',
            },
        ),
        migrations.CreateModel(
            name='AdditionalOrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=50)),
                ('sender', models.CharField(max_length=50)),
                ('comments', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.NewOrder')),
            ],
            options={
                'verbose_name': 'Dodatkowe szczegóły zamówień',
                'verbose_name_plural': 'Dodatkowe szczegóły zamówień',
            },
        ),
    ]
