# Generated by Django 2.2.4 on 2020-09-15 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=500, verbose_name='Nazwa firmy')),
                ('company_phone', models.CharField(max_length=30, verbose_name='Telefon kontaktowy')),
                ('description', models.TextField(verbose_name='Opis firmy')),
                ('nip', models.CharField(max_length=20, verbose_name='NIP')),
                ('regon', models.CharField(max_length=20, verbose_name='REGON')),
                ('city', models.CharField(max_length=250, verbose_name='Miasto')),
                ('street', models.CharField(max_length=250, verbose_name='Ulica')),
                ('zip_code', models.CharField(max_length=20, verbose_name='Kod pocztowy')),
                ('province', models.CharField(choices=[('Mazowieckie', 'Mazowieckie'), ('Śląskie', 'Śląskie'), ('Wielkopolskie', 'Wielkopolskie'), ('Małopolskie', 'Małopolskie'), ('Dolnośląskie', 'Dolnośląskie'), ('Łódzkie', 'Łódzkie'), ('Pomorskie', 'Pomorskie'), ('Podkarpackie', 'Podkarpackie'), ('Lubelskie', 'Lubelskie'), ('Kujawsko-pomorskie', 'Kujawsko-pomorskie'), ('Zachodniopomorskie', 'Zachodniopomorskie'), ('Warmińsko-mazurskie', 'Warmińsko-mazurskie'), ('Świętokrzyskie', 'Świętokrzyskie'), ('Podlaskie', 'Podlaskie'), ('Lubuskie', 'Lubuskie'), ('Opolskie', 'Opolskie')], max_length=100, verbose_name='Województwo')),
                ('package', models.CharField(max_length=50, verbose_name='Pakiet')),
                ('blocked', models.CharField(max_length=50, verbose_name='Zablokowany')),
                ('logo', models.ImageField(upload_to='', verbose_name='Logo')),
                ('thumbnail', models.ImageField(upload_to='', verbose_name='Miniatura')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Właściciel')),
            ],
            options={
                'verbose_name': 'Firmy',
                'verbose_name_plural': 'Firmy',
            },
        ),
        migrations.AlterModelOptions(
            name='neworder',
            options={'verbose_name': 'Wyceny', 'verbose_name_plural': 'Wyceny'},
        ),
        migrations.AlterField(
            model_name='neworder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia'),
        ),
        migrations.AlterField(
            model_name='neworder',
            name='custom_id',
            field=models.IntegerField(verbose_name='ID użytkownika'),
        ),
        migrations.AlterField(
            model_name='neworder',
            name='date',
            field=models.DateTimeField(verbose_name='Data wysłania paczki'),
        ),
        migrations.AlterField(
            model_name='neworder',
            name='depth',
            field=models.PositiveIntegerField(verbose_name='Długość paczki'),
        ),
        migrations.AlterField(
            model_name='neworder',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Adres email'),
        ),
        migrations.AlterField(
            model_name='neworder',
            name='height',
            field=models.PositiveIntegerField(verbose_name='Wysokość paczki'),
        ),
        migrations.AlterField(
            model_name='neworder',
            name='image_1',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='profile-pictures', verbose_name='Zdjęcie poglądowe 1'),
        ),
        migrations.AlterField(
            model_name='neworder',
            name='image_2',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='profile-pictures', verbose_name='Zdjęcie poglądowe 2'),
        ),
        migrations.AlterField(
            model_name='neworder',
            name='image_3',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='profile-pictures', verbose_name='Zdjęcie poglądowe 3'),
        ),
        migrations.AlterField(
            model_name='neworder',
            name='items_descriptions',
            field=models.TextField(verbose_name='Opis przedmiotu'),
        ),
        migrations.AlterField(
            model_name='neworder',
            name='location_name_from',
            field=models.CharField(max_length=500, verbose_name='Lokalizacja nadawcy'),
        ),
        migrations.AlterField(
            model_name='neworder',
            name='location_name_to',
            field=models.CharField(max_length=500, verbose_name='Lokalizacja odbiorcy'),
        ),
        migrations.AlterField(
            model_name='neworder',
            name='org_latitude_form',
            field=models.IntegerField(verbose_name='Współrzedne nadawcy (Szerokość geograficzna)'),
        ),
        migrations.AlterField(
            model_name='neworder',
            name='org_latitude_to',
            field=models.IntegerField(verbose_name='Współrzedne odbiorcy (Szerokość geograficzna)'),
        ),
        migrations.AlterField(
            model_name='neworder',
            name='org_longitude_from',
            field=models.IntegerField(verbose_name='Współrzedne nadawcy (Długość geograficzna)'),
        ),
        migrations.AlterField(
            model_name='neworder',
            name='org_longitude_to',
            field=models.IntegerField(verbose_name='Współrzedne odbiorcy (Długość geograficzna)'),
        ),
        migrations.AlterField(
            model_name='neworder',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='Numer telefonu'),
        ),
        migrations.AlterField(
            model_name='neworder',
            name='type_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.TypeProduct', verbose_name='Typ produktu'),
        ),
        migrations.AlterField(
            model_name='neworder',
            name='unique_url',
            field=models.URLField(verbose_name='URL przesyłki'),
        ),
        migrations.AlterField(
            model_name='neworder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data edycji'),
        ),
        migrations.AlterField(
            model_name='neworder',
            name='weight',
            field=models.PositiveIntegerField(verbose_name='Waga paczki'),
        ),
        migrations.AlterField(
            model_name='neworder',
            name='width',
            field=models.PositiveIntegerField(verbose_name='Szerokość paczki'),
        ),
        migrations.AlterField(
            model_name='typeproduct',
            name='icons',
            field=models.ImageField(upload_to='', verbose_name='Zdjęcie'),
        ),
        migrations.AlterField(
            model_name='typeproduct',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nazwa typu produktu'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Cena')),
                ('package', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.CompanyUser')),
            ],
        ),
        migrations.CreateModel(
            name='OfferResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Cena')),
                ('date', models.DateTimeField(verbose_name='Data')),
                ('comments', models.TextField(verbose_name='Komentarz')),
                ('displayed', models.BooleanField(default=True, verbose_name='Pokaż oferte')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.CompanyUser', verbose_name='Firma')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.NewOrder', verbose_name='Właściciel')),
            ],
            options={
                'verbose_name': 'Odpowiedzi na oferty',
                'verbose_name_plural': 'Odpowiedzi na oferty',
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('owner', models.CharField(max_length=75)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data edycji')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Category')),
            ],
        ),
    ]
