# Generated by Django 2.2.4 on 2020-09-15 16:46

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_auto_20200915_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Parametrs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_obj', models.IntegerField()),
                ('par_name', models.CharField(max_length=200)),
                ('par_value', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('par_active', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms', ckeditor.fields.RichTextField(verbose_name='Polityka prywatności')),
                ('conditions', ckeditor.fields.RichTextField(verbose_name='Regulamin strony')),
            ],
            options={
                'verbose_name': 'Polityka prywatności i regulamin strony',
                'verbose_name_plural': 'Polityka prywatności i regulamin strony',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategorie', 'verbose_name_plural': 'Kategorie'},
        ),
        migrations.AlterModelOptions(
            name='newsletter',
            options={'verbose_name': 'NewsLetter - artykuły', 'verbose_name_plural': 'NewsLetter - artykuły'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Płatności i statusy', 'verbose_name_plural': 'Płatności i statusy'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nazwa kategorii'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Category', verbose_name='Kategoria'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='content',
            field=models.TextField(verbose_name='Treść postu'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='owner',
            field=models.CharField(max_length=75, verbose_name='Autor postu'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='topic',
            field=models.CharField(max_length=50, verbose_name='Temat postu'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.CompanyUser', verbose_name='Własciciel'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='package',
            field=models.CharField(max_length=50, verbose_name='Pakiet'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(max_length=50, verbose_name='Status płatności'),
        ),
        migrations.CreateModel(
            name='Coments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, verbose_name='Nazwa użytkownika')),
                ('content', models.CharField(max_length=50, verbose_name='Treść komentarza')),
                ('displayed', models.BooleanField(verbose_name='Pokaż komentarz')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Newsletter', verbose_name='Post')),
            ],
            options={
                'verbose_name': 'Komentarze',
                'verbose_name_plural': 'Komentarze',
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date', models.DateTimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Instancje czatu',
                'verbose_name_plural': 'Instancje czatu',
            },
        ),
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('change', models.TextField()),
                ('date', models.DateTimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Logi zmian',
                'verbose_name_plural': 'Logi zmian',
            },
        ),
        migrations.CreateModel(
            name='AdditionalOrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=50)),
                ('sender', models.CharField(max_length=50)),
                ('comments', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.NewOrder')),
            ],
            options={
                'verbose_name': 'Dodatkowe szczegóły zamówień',
                'verbose_name_plural': 'Dodatkowe szczegóły zamówień',
            },
        ),
    ]
