# Generated by Django 2.2.4 on 2020-09-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200915_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyuser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='companyuser',
            name='province',
        ),
        migrations.RemoveField(
            model_name='companyuser',
            name='street',
        ),
        migrations.RemoveField(
            model_name='companyuser',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='companyuser',
            name='location',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
