# Generated by Django 2.2.4 on 2020-09-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20200915_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyuser',
            name='regon',
        ),
        migrations.AddField(
            model_name='companyuser',
            name='company_email',
            field=models.EmailField(default=1, max_length=254, verbose_name='Adres email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyuser',
            name='licence',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
