# Generated by Django 2.2.4 on 2020-09-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20200915_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuser',
            name='contact_person',
            field=models.CharField(default=1, max_length=50, verbose_name='Osoba kontaktowa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyuser',
            name='directions_supported',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyuser',
            name='vehicle_fleet',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='licence',
            field=models.FileField(upload_to='', verbose_name='Licencja'),
        ),
    ]
