# Generated by Django 2.2.4 on 2020-10-07 07:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20200915_1919'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'verbose_name': 'NewsLetter/Blog - artykuły', 'verbose_name_plural': 'NewsLetter/Blog - artykuły'},
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Treść postu'),
        ),
    ]
