# Generated by Django 2.2.4 on 2020-10-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20201007_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='displayed_in_navbar',
            field=models.BooleanField(default=False),
        ),
    ]
