# Generated by Django 2.2.4 on 2020-10-07 08:44

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_category_displayed_in_navbar'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='img',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='profile-pictures', verbose_name='Zdjęcie artykułu'),
        ),
    ]
