# Generated by Django 2.2.4 on 2020-10-07 08:48

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_newsletter_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='img',
            field=imagekit.models.fields.ProcessedImageField(default=1, upload_to='profile-pictures', verbose_name='Zdjęcie artykułu'),
            preserve_default=False,
        ),
    ]
