# Generated by Django 2.2.4 on 2020-10-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20201007_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='sub_title',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
