# Generated by Django 2.2.4 on 2020-10-07 09:28

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_newsletter_sub_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='bg_img',
            field=imagekit.models.fields.ProcessedImageField(default=1, upload_to='profile-pictures'),
            preserve_default=False,
        ),
    ]
