# Generated by Django 2.2.4 on 2020-10-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_newsletter_bg_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'ordering': ['-created_at'], 'verbose_name': 'NewsLetter/Blog - artykuły', 'verbose_name_plural': 'NewsLetter/Blog - artykuły'},
        ),
        migrations.AlterField(
            model_name='typeproduct',
            name='icons',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Zdjęcie'),
        ),
    ]
