# Generated by Django 2.2 on 2020-10-14 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customuser_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='online',
            field=models.IntegerField(default=0),
        ),
    ]
