# Generated by Django 2.2.4 on 2020-09-15 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userhelpedelement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userhelpedelement',
            options={'verbose_name': 'Dodatkowe infomacje o koncie', 'verbose_name_plural': 'Dodatkowe infomacje o koncie'},
        ),
        migrations.AlterField(
            model_name='userhelpedelement',
            name='last_login',
            field=models.DateTimeField(verbose_name='Ostatnie logowanie'),
        ),
        migrations.AlterField(
            model_name='userhelpedelement',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Właściciel'),
        ),
        migrations.AlterField(
            model_name='userhelpedelement',
            name='type_account',
            field=models.CharField(max_length=50, verbose_name='Typ konta'),
        ),
        migrations.AlterField(
            model_name='userhelpedelement',
            name='verified',
            field=models.BooleanField(verbose_name='Konto zweryfikowane'),
        ),
    ]
