# Generated by Django 2.2.4 on 2020-09-16 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20200915_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhelpedelement',
            name='money',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userhelpedelement',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userhelpedelement',
            name='surname',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userhelpedelement',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='profile-pictures'),
        ),
        migrations.CreateModel(
            name='CompanyUserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=500)),
                ('nip', models.CharField(max_length=20)),
                ('province', models.CharField(choices=[('Mazowieckie', 'Mazowieckie'), ('Śląskie', 'Śląskie'), ('Wielkopolskie', 'Wielkopolskie'), ('Małopolskie', 'Małopolskie'), ('Dolnośląskie', 'Dolnośląskie'), ('Łódzkie', 'Łódzkie'), ('Pomorskie', 'Pomorskie'), ('Podkarpackie', 'Podkarpackie'), ('Lubelskie', 'Lubelskie'), ('Kujawsko-pomorskie', 'Kujawsko-pomorskie'), ('Zachodniopomorskie', 'Zachodniopomorskie'), ('Warmińsko-mazurskie', 'Warmińsko-mazurskie'), ('Świętokrzyskie', 'Świętokrzyskie'), ('Podlaskie', 'Podlaskie'), ('Lubuskie', 'Lubuskie'), ('Opolskie', 'Opolskie')], max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=150)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Właściciel')),
            ],
            options={
                'verbose_name': 'Dane użytkownika do faktury',
                'verbose_name_plural': 'Dane użytkownika do faktury',
            },
        ),
    ]
