# Generated by Django 2.2.4 on 2020-09-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20200916_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userhelpedelement',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='userhelpedelement',
            name='money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
