# Generated by Django 2.2.4 on 2020-09-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20200916_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userhelpedelement',
            name='last_login',
        ),
        migrations.AlterField(
            model_name='userhelpedelement',
            name='basic',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userhelpedelement',
            name='type_account',
            field=models.CharField(default='Standard', max_length=50, verbose_name='Typ konta'),
        ),
        migrations.AlterField(
            model_name='userhelpedelement',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Konto zweryfikowane'),
        ),
    ]
