# Generated by Django 2.2.4 on 2020-09-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20200916_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuserdata',
            name='zip_code',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
